//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>
#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>

#import "SCComposerViewOwner-Protocol.h"
#import "SCContextV2ActionsHandlerDelegate-Protocol.h"
#import "SCContextV2SwipeUpPresentable-Protocol.h"
#import "SCPageNameLogging-Protocol.h"
#import "SCShakeToReportDelegate-Protocol.h"


@class NSLayoutConstraint, NSString, SCContextActionParams, SCContextLoggingActionSource, SCContextSessionParams, SCContextV2ActionMenuViewController, SCContextV2ActionsHandler, SCContextV2CardsView, SCLazy, SCObservable, UIScrollView, UIStackView, UIView;
@protocol SCContextLogging, SCContextV2SwipeUpViewControllerDelegate, SCContextV3ActionHandlerProviding, SCNavigationLogging;

@interface SCContextV2SwipeUpViewController : UIViewController <UIScrollViewDelegate, UIGestureRecognizerDelegate, SCShakeToReportDelegate, SCComposerViewOwner, SCContextV2ActionsHandlerDelegate, SCContextV2SwipeUpPresentable, SCPageNameLogging>
{
    id <SCContextLogging> _logger;
    UIScrollView *_scrollView;
    UIStackView *_stackView;
    SCContextV2CardsView *_cardsView;
    _Bool _nonInteractiveDismissalInProgress;
    _Bool _dismissAtEndOfScroll;
    _Bool _presentationGestureInProgress;
    _Bool _scrollViewHasBeenGrabbed;
    id <SCContextV3ActionHandlerProviding> _v3ActionHandlerProvider;
    SCContextActionParams *_actionParams;
    NSLayoutConstraint *_replyViewHeightConstraint;
    SCContextV2ActionMenuViewController *_actionMenuViewController;
    SCObservable *_operaPageObservable;
    SCLazy *_birthdayProvider;
    SCLazy *_bitmojiAvatarProvider;
    SCLazy *_imageDownloader;
    SCLazy *_storiesFetcher;
    SCLazy *_storyHandler;
    SCLazy *_viewLoader;
    id _onDismissal;
    id _onContentSizeChange;
    SCContextLoggingActionSource *_contextActionSource;
    id <SCContextV2SwipeUpViewControllerDelegate> _delegate;
    UIView *_replyView;
    double _replyViewHeight;
    double _cardsAndActionsOpacity;
    SCContextV2ActionsHandler *_actionsHandler;
    SCContextSessionParams *_sessionParams;
}

@property(readonly, nonatomic) SCContextSessionParams *sessionParams; // @synthesize sessionParams=_sessionParams;
@property(readonly, nonatomic) SCContextV2ActionsHandler *actionsHandler; // @synthesize actionsHandler=_actionsHandler;
@property(nonatomic) double cardsAndActionsOpacity; // @synthesize cardsAndActionsOpacity=_cardsAndActionsOpacity;
@property(nonatomic) double replyViewHeight; // @synthesize replyViewHeight=_replyViewHeight;
@property(retain, nonatomic) UIView *replyView; // @synthesize replyView=_replyView;
@property(nonatomic) __weak id <SCContextV2SwipeUpViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) SCContextLoggingActionSource *contextActionSource; // @synthesize contextActionSource=_contextActionSource;
@property(copy, nonatomic) id onContentSizeChange; // @synthesize onContentSizeChange=_onContentSizeChange;
@property(copy, nonatomic) id onDismissal; // @synthesize onDismissal=_onDismissal;
- (void)didTapDoneButton;	// IMP=0x000000010514fb3c
- (id)defaultProjectNameV2;	// IMP=0x000000010514fb30
- (void)setPresentationAmount:(double)arg1 gestureTracker:(id)arg2;	// IMP=0x000000010514fab8
- (void)gestureTracker:(id)arg1 isActivelyAnimatingPresentationAmount:(_Bool)arg2;	// IMP=0x000000010514faa8
- (double)initialSwipeUpGesturePresentationAmount:(id)arg1;	// IMP=0x000000010514fa9c
- (double)initialPresentationAmount;	// IMP=0x000000010514fa20
- (void)presentFromBaseViewController:(id)arg1 gestureTracker:(id)arg2 completion:(id)arg3;	// IMP=0x000000010514f90c
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;	// IMP=0x000000010514f784
- (void)scrollViewWillBeginDragging:(id)arg1;	// IMP=0x000000010514f764
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;	// IMP=0x000000010514f5a0
- (void)scrollViewDidScroll:(id)arg1;	// IMP=0x000000010514f3c0
- (double)_maxPresentationAmount;	// IMP=0x000000010514f36c
- (void)contextActionsHandlerWantsToDismissCurrentModalOverlay:(id)arg1 completion:(id)arg2;	// IMP=0x000000010514f368
- (void)contextActionsHandlerWantsToOpenChat:(id)arg1 source:(id)arg2;	// IMP=0x000000010514f320
- (void)contextActionsHandler:(id)arg1 didLeaveAppSuccessfully:(_Bool)arg2;	// IMP=0x000000010514f2c8
- (void)contextActionsHandlerWillTryToLeaveApp:(id)arg1;	// IMP=0x000000010514f280
- (void)contextActionsHandlerDidFinishPresentingMedia:(id)arg1;	// IMP=0x000000010514f238
- (void)contextActionsHandlerDidBeginPresentingMedia:(id)arg1;	// IMP=0x000000010514f1f0
- (void)contextActionsHandlerDidDismissModalContent:(id)arg1 source:(id)arg2;	// IMP=0x000000010514f1a8
- (void)contextActionsHandlerDidPresentModalContent:(id)arg1 source:(id)arg2;	// IMP=0x000000010514f1a4
- (void)contextActionsHandler:(id)arg1 wantsToDismissContextCardsWithCompletion:(id)arg2;	// IMP=0x000000010514f194
- (void)_addReplyView;	// IMP=0x000000010514f030
- (void)showErrorStateWithRetryBlock:(id)arg1;	// IMP=0x000000010514eea8
- (id)cardsContent;	// IMP=0x000000010514ee90
- (void)showCardsContent:(id)arg1;	// IMP=0x000000010514edf4
- (void)showPlaceholderCards:(id)arg1;	// IMP=0x000000010514ed7c
- (id)pageViewName;	// IMP=0x000000010514ed6c
- (void)dismissViewControllerAnimated:(_Bool)arg1 completion:(id)arg2;	// IMP=0x000000010514eac4
- (void)_tappedToDismiss;	// IMP=0x000000010514eab0
- (void)contentSizeDidChange;	// IMP=0x000000010514e940
- (void)viewDidDisappear:(_Bool)arg1;	// IMP=0x000000010514e880
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x000000010514e7c0
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x000000010514e710
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x000000010514e660
- (void)viewDidLoad;	// IMP=0x000000010514d520
- (id)initWithSessionParams:(id)arg1 logger:(id)arg2 v3ActionHandlerProvider:(id)arg3 actionParams:(id)arg4 operaPageObservable:(id)arg5 birthdayProvider:(id)arg6 bitmojiAvatarProvider:(id)arg7 imageDownloader:(id)arg8 storiesFetcher:(id)arg9 storyHandler:(id)arg10 composerViewLoader:(id)arg11;	// IMP=0x000000010514d2c0

// Remaining properties
@property(retain, nonatomic) id <SCNavigationLogging> PPVNavigationLogger;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) NSUInteger hash;
@property(readonly) Class superclass;

@end

