//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCSearchCollectionViewCell.h"

#import "SCActionable-Protocol.h"
#import "SCDiscoverFeedStoryTileWithBloopsConfigurable-Protocol.h"
#import "SCDiscoverFeedStoryTileWithCoverImageConfigurable-Protocol.h"
#import "SCDiscoverFeedStoryTileWithVideoConfigurable-Protocol.h"
#import "SCDiscoverFeedTileOperaBaseViewProviding-Protocol.h"
#import "SCEventAnnouncing-Protocol.h"
#import "SCEventListener-Protocol.h"
#import "SCRoundedCornerConfigurable-Protocol.h"
#import "SCViewModelConfigurable-Protocol.h"

@class NSString, SCActionModel, SCDiscoverFeedDebugView, SCDiscoverFeedLabelOverlayView, SCEventListenerAnnouncer, SCLazy, SCNetworkImageView, SCNetworkVideo, SCNetworkVideoView, SCRoundedCornerContainerView, UILabel, UIView;
@protocol SCActionHandling, SCCanceling, SCImageDownloading, SCLegacyItemDownloading;

@interface SCDiscoverFeedStoryCollectionViewCell : SCSearchCollectionViewCell <UIGestureRecognizerDelegate, SCEventAnnouncing, SCEventListener, SCRoundedCornerConfigurable, SCViewModelConfigurable, SCActionable, SCViewportConfigurable, SCDiscoverFeedStoryTileWithVideoConfigurable, SCDiscoverFeedStoryTileWithCoverImageConfigurable, SCDiscoverFeedTileOperaBaseViewProviding, SCDiscoverFeedStoryTileWithBloopsConfigurable>
{
    UIView *_backgroundView;
    UIView *_thumbnailCornerContainer;
    UIView *_thumbnailCornerContainerContentView;
    id _storyCoverImageView;
    id _storyCoverVideoView;
    id _tileOverlayView;
    id _dynamicReplayOverlayViewLazy;
    UIView *_labelOverlayView;
    id *_logoOverlayViewLazy;
    UIView *_debugView;
    UILabel *_playerDebugLabel;
    UILabel *_snapDocDebugLabel;
    id _primaryTapActionModel;
    id _secondaryTapActionModel;
    id _longPressActionModel;
    id _scrollOutOfScreenActionModel;
    id _videoThumbnail;
    _Bool _isVideoThumbnailPlaying;
    _Bool _hasFirstFrameImage;
    struct CGPoint _lastOrigin;
    double _lastOriginCaptureTime;
    id _eventAnnouncer;
    id _cancelationToken;
    unsigned long long _roundedCorners;
    id <SCActionHandling> _actionHandler;
    id _viewModel;
    id <SCImageDownloading> _imageDownloader;
    id <SCLegacyItemDownloading> _videoDownloader;
    id _bloopsDiscoverTileProvider;
    struct CGRect _viewportFrame;
}

+ (struct CGSize)sizeWithViewModel:(id)arg1 constrainedToSize:(struct CGSize)arg2;    // IMP=0x00000001005942b4
+ (id)announcerIdentifier;    // IMP=0x000000010640d0c0
@property(retain, nonatomic) id viewModel; // @synthesize viewModel=_viewModel;
@property(retain, nonatomic) id actionHandler; // @synthesize actionHandler=_actionHandler;
@property(nonatomic) unsigned long long roundedCorners; // @synthesize roundedCorners=_roundedCorners;
- (void)_calculateCellFrameAndDispatchEventIfNecessary:(id)arg1 announcerIdentifier:(id)arg2 extraData:(id)arg3;    // IMP=0x000000010640fc94
- (void)didTriggerEventWithEventName:(id)arg1 announcerIdentifier:(id)arg2 extraData:(id)arg3;    // IMP=0x000000010640fad0
- (void)_handleLongPressAction:(id)arg1;    // IMP=0x000000010640fa00
- (void)_handleTapAction:(id)arg1;    // IMP=0x000000010640f88c
- (void)stopVideoPlaybackAndEndSession;    // IMP=0x000000010640f874
- (_Bool)isVideoThumbnailPlaying;    // IMP=0x000000010640f840
- (void)restartVideoPlayback;    // IMP=0x000000010640f83c
- (void)resumeVideoPlaybackIfPossible;    // IMP=0x000000010640f80c
- (void)pauseVideoPlaybackIfPossible;    // IMP=0x000000010640f7b0
- (void)_setupCoverVideoViewWithImage:(id)arg1 viewModel:(id)arg2;    // IMP=0x000000010640f718
- (void)_debugGesture:(id)arg1;    // IMP=0x000000010640f62c
- (void)_setupDebugViewIfNeeded:(id)arg1;    // IMP=0x000000010640f4dc
- (void)_playVideoThumbnail;    // IMP=0x000000010640f37c
- (void)_setupCoverVideoViewWithVideoThumbnail:(id)arg1;    // IMP=0x000000010640f108
- (void)_updateWithViewModel:(id)arg1;    // IMP=0x000000010640e384
- (void)_layoutWithViewModel;    // IMP=0x000000010640dcc4
- (void)_compareAndUpdateViewModelIfNeeded:(id)arg1;    // IMP=0x000000010640dc6c
- (id)operaBaseView;    // IMP=0x000000010640dc60
- (void)prepareForReuse;    // IMP=0x000000010640db5c
- (void)_handleScrollOutOfScreenAction;    // IMP=0x000000010640daec
- (void)viewportDidUpdateViewportFrame:(struct CGRect)arg1 dragging:(_Bool)arg2 decelerating:(_Bool)arg3;    // IMP=0x000000010640d7e0
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;    // IMP=0x000000010640d78c
- (void)layoutSubviews;    // IMP=0x000000010640d73c
- (id)storyCoverImage;    // IMP=0x000000010640d710
- (id)initWithFrame:(struct CGRect)arg1;    // IMP=0x000000010640d0fc
- (void)removeListener:(id)arg1;    // IMP=0x000000010640d0e4
- (void)addListener:(id)arg1;    // IMP=0x000000010640d0cc

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end
