//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May  5 2020 12:41:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SCScalingButton.h"

@interface SCGrowingButton : SCScalingButton
{
    double _maximumScale;
    double _minimumScale;
}

@property(nonatomic) double minimumScale; // @synthesize minimumScale=_minimumScale;
@property(nonatomic) double maximumScale; // @synthesize maximumScale=_maximumScale;
- (id)initWithFrame:(struct CGRect)arg1;

@end

