#import <objc/NSObject.h>

@class NSString, SCNMessagingMessageAnalytics, SCNMessagingMessageContent, SCNMessagingMessageDescriptor, SCNMessagingMessageMetadata, SCNMessagingUUID;

@interface SCNMessagingMessage : NSObject {
    SCNMessagingMessageDescriptor *_descriptor;
    SCNMessagingUUID *_senderId;
    SCNMessagingMessageContent *_messageContent;
    SCNMessagingMessageMetadata *_metadata;
    long long _releasePolicy;
    long long _state;
    SCNMessagingMessageAnalytics *_messageAnalytics;
    long long _orderKey;
}

@property(readonly, nonatomic) long long orderKey;
@property(readonly, nonatomic) SCNMessagingMessageAnalytics *messageAnalytics;
@property(readonly, nonatomic) long long state;
@property(readonly, nonatomic) long long releasePolicy;
@property(readonly, nonatomic) SCNMessagingMessageMetadata *metadata;
@property(readonly, nonatomic) SCNMessagingMessageContent *messageContent;
@property(readonly, nonatomic) SCNMessagingUUID *senderId;
@property(readonly, nonatomic) SCNMessagingMessageDescriptor *descriptor;
- (id)initWithDescriptor:(id)arg1 senderId:(id)arg2 messageContent:(id)arg3 metadata:(id)arg4 releasePolicy:(long long)arg5 state:(long long)arg6 messageAnalytics:(id)arg7 orderKey:(long long)arg8;
- (id)quotedMessageContent;
- (_Bool)isChatReply;
- (id)contents;
- (id)snapReportId;
- (id)cognacParticipantIds;
- (_Bool)isCognacGameClosedStatusMessage;
- (_Bool)isProfileMediaMessage;
- (id)snapchatterUserId;
- (_Bool)isAttachmentMessage;
- (_Bool)isSilentMessage;
- (id)textMediaAttributes;
- (id)textFormatAttributes:(id)arg1;
- (id)getAddresses;
- (id)getUrls;
- (_Bool)disableSwipeUpReply;
- (_Bool)isErasedSnapStatusMessage;
- (id)readByParticipants;
- (_Bool)isErased;
- (_Bool)isErasableBy:(id)arg1 chatMessageHandlerMap:(id)arg2;
- (id)screenRecordingState;
- (id)screenshotState;
- (id)replayParticipants;
- (id)lastToReplay;
- (id)lastToScreenshot;
- (_Bool)wouldBeExpiredIfNotSaved;
- (unsigned long long)numMedias;
- (long long)mediaType;
- (id)mediaList;
- (_Bool)mediaHasLoaded;
- (_Bool)isUnexpiredOneOnOneSnap;
- (_Bool)isSent;
- (_Bool)isBloopMessage;
- (_Bool)isLagunaMessage;
- (_Bool)isExpired;
- (_Bool)hasAudio;
- (id)getReplyMediaById:(id)arg1;
- (id)getReplyMedia;
- (void)getMediasWithCompletionHandler:(id)arg1;
- (id)getMediaById:(id)arg1;
- (id)_expirationByAddingRetentionInMinutes:(double)arg1 toDate:(id)arg2;
- (id)_dateToCalculateExpirationForIsGroupMessage:(_Bool)arg1;
- (double)expirationTimerPiePercentageForIsGroupMessage:(_Bool)arg1 retentionInMinutes:(double)arg2;
- (id)expirationDate;
- (_Bool)containsVideo;
- (_Bool)containsSpectacles;
- (_Bool)allMediasUploaded;
- (id)textMessageSignature;
- (id)snapOldestOpenTimestamp;
- (id)snapNewestOpenTimestamp;
- (_Bool)shouldShowUnreadChatIcon;
- (_Bool)shouldShowReplayAnimation;
- (_Bool)shouldHideSendState;
- (long long)replayStateForViewer:(id)arg1;
- (id)recipient;
- (_Bool)isViewing;
- (_Bool)isViewedOneOnOneOrSentGroupSnapBy:(id)arg1 messageMetadata:(id)arg2;
- (_Bool)isUpdateMessageFrom:(id)arg1;
- (_Bool)isUpdateMessage;
- (_Bool)isTextStoryReplyMessage;
- (_Bool)isTextMessage;
- (_Bool)isStorySnapMessage;
- (_Bool)isStoryReplyMessage;
- (_Bool)isStoryContentMessage;
- (_Bool)isStickerMessage;
- (_Bool)isSnapchatterMessage;
- (_Bool)isSnapMessage;
- (_Bool)isSentBy:(id)arg1;
- (_Bool)isSendingOrCanBeRetried;
- (_Bool)isSearchStoryMessage;
- (_Bool)isSearchDynamicStoriesMessage;
- (_Bool)isScreenshotted;
- (_Bool)isReplayed;
- (_Bool)isReadBy:(id)arg1;
- (_Bool)isPreservedBy:(id)arg1;
- (_Bool)isPreservableType;
- (_Bool)isParticipantLeftMessage;
- (_Bool)isOpenedByAtleastOneRecipient;
- (_Bool)isOpenedBy:(id)arg1;
- (_Bool)isMissedVideoCallMessage;
- (_Bool)isSavedSnapMessage;
- (_Bool)isChatMentionForUsername:(id)arg1;
- (_Bool)isMissedAudioCallMessage;
- (_Bool)isMediaSaveMessage;
- (_Bool)isMessageOnBirthday:(id)arg1;
- (_Bool)isMemoryStoryMessage;
- (_Bool)isMediaContentMessage;
- (_Bool)isChatMediaMessage;
- (_Bool)isMapSnapMessage;
- (_Bool)isCashMessage;
- (_Bool)isBroadcastSnap;
- (_Bool)hasMediaCards;
- (id)mentionedUserIds;
- (id)chatOldestOpenTimestamp;
- (_Bool)canBeSaved;
- (_Bool)isLoadedReplayableBySelf:(id)arg1;
- (_Bool)canBeReplayed;
- (id)broadcastSnapSignature;
- (_Bool)isUnseenMessage:(id)arg1;
- (_Bool)isForwardable;
- (_Bool)isUnreadByRecipients;
- (_Bool)_isUnseenByRecipients;
- (id)messageTimestampForOrdering;
- (_Bool)canDelete;
- (long long)messageType;
- (_Bool)sending;
- (_Bool)failedToSend;
- (_Bool)isSendingOrHasFailed;
- (id)savedParticipants;
- (_Bool)isSavedByParticipant:(id)arg1;
- (_Bool)isSaved;
- (_Bool)isReleasedBy:(id)arg1;
- (_Bool)isReleased;
- (id)sequenceNumber;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (unsigned long long)retentionInMinutes;
- (_Bool)markedForDeletionByServer;
- (long long)screenCaptureSource;
- (_Bool)isScreenRecording;
- (id)messageParcel;
- (id)messageParcelType;
- (id)replyMedias;
- (_Bool)isSavedToMemories;
- (_Bool)isPendingSnap;
- (id)snapServerId;
- (_Bool)isSnapEnvelopeReleased;
- (_Bool)shouldRetryMediaSendTask;
- (id)typeVersion;
- (unsigned long long)mischiefVersion;
- (long long)groupId;
- (long long)sendStatus;
- (id)mediaSave;
- (id)searchStoryShare;
- (id)searchSnapShare;
- (id)nycShare;
- (id)khaleesiShare;
- (id)snapchatterShare;
- (id)mediaSendTaskId;
- (id)mediaSendTaskClientMessageId;
- (id)storyShare;
- (long long)speedwayStoryV2Source;
- (id)storyTitle;
- (id)encryptedGeoData;
- (id)snapMetadata;
- (id)groupUpdate;
- (id)_groupUpdateForGroupInviteLinkStatusMessage:(id)arg1;
- (id)_groupUpdateForParticipantChangeStatusMessage:(id)arg1;
- (id)_groupUpdateForNameChange:(id)arg1;
- (id)_groupUpdateForGroupCreation:(id)arg1;
- (id)snapProStoryReplyInfo;
- (id)chatSticker;
- (id)medias;
- (id)overlayMedia;
- (id)media;
- (id)mediaCardAttributes;
- (id)attributes;
- (id)text;
- (long long)type;
- (id)snapState;
- (id)preserveState;
- (id)releaseState;
- (id)savedState;
- (id)iterToken;
- (id)sendStartTimestamp;
- (id)sentTimestamp;
- (id)messageTimestamp;
- (id)knownChatSequenceNumbers;
- (id)recipientForOneOnOneChat;
- (_Bool)isUnknownMessageForParcelMap:(id)arg1;
- (_Bool)isStatusMessageForParcelMap:(id)arg1;
- (id)messageRecipientIdentifierForOneOnOne;
- (id)conversationId;
- (id)messageSenderIdentifier;
- (id)messageSender;
- (id)encryptedId;
- (id)clientMessageId;
- (id)analyticsMessageId;
- (id)consistentId;

@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) NSUInteger hash;
@property(readonly) Class superclass;

@end
