//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>


@class NSArray, NSMutableArray, NSMutableDictionary, NSNotificationCenter, NSString, SCCustomVolumeController, SCOperaAttachmentInteractionController, SCOperaConfiguration, SCOperaDependencies, SCOperaLayerViewControllerConfiguration, SCOperaPageLayersSnapshotsTracker, SCOperaPageViewController, SCOperaSharedResourceManager, SCOperaTriggerPointsManager, SCOperaViewControllerLifecycleWorkaroundHelper, SCOperaViewInteraction, SCOperaViewModel, SCOperaViewModelsManager;
@protocol SCModalPresentation, SCNavigationLogging, SCOperaCurrentViewModelPagePropertiesProviding, SCOperaEventAnnouncing, SCOperaInteractionStateProviding, SCOperaLegacySessionStateContaining, SCOperaNavigationManaging, SCOperaScrollViewLayoutManaging, SCOperaShakeToReportOperator, SCOperaShareableMediaItemsProviding, SCOperaUIViewControllerProviding, SCOperaViewModelConnectionsCallbackControlling, SCOperaViewPlayManaging, SCOperaZooming, SCViewControllerTransitionAnimating;

@interface SCOperaViewController : UIViewController
@property(readonly, nonatomic) id  eventAnnouncer; // @synthesize eventAnnouncer=_eventAnnouncer;
@property(nonatomic) _Bool disableSwipeDownToDismiss; // @synthesize disableSwipeDownToDismiss=_disableSwipeDownToDismiss;
@property(readonly, nonatomic) SCOperaConfiguration *configuration; // @synthesize configuration=_configuration;
@property(readonly, nonatomic) SCOperaDependencies *operaDependencies; // @synthesize operaDependencies=_operaDependencies;
@property(readonly, nonatomic) SCOperaViewInteraction *lastInteraction; // @synthesize lastInteraction=_lastInteraction;
- (struct CGSize)_operaScrollViewContentSizeForPageSize:(struct CGSize)arg1;	// IMP=0x00000001066f1704
- (struct CGSize)_pageSizePlusMarginForCurrentViewBounds;	// IMP=0x00000001066f1674
- (void)_resumeIfNotInBackground;	// IMP=0x00000001066f15f4
- (_Bool)_isPaused;	// IMP=0x00000001066f15d8
- (void)_applyPausedUIIfNeeded;	// IMP=0x00000001066f144c
- (void)_pauseIfAppIsInBackground;	// IMP=0x00000001066f13c8
- (void)_updateStatusBarAnimated:(_Bool)arg1;	// IMP=0x00000001066f1238
- (void)_callViewDidAppearImplIfNeeded;	// IMP=0x00000001066f10bc
- (void)_viewDidAppearImpl;	// IMP=0x00000001066f0c7c
- (void)_setNeedsUpdatePageVCsBasedOnViewModels;	// IMP=0x00000001066f0c34
- (void)_addSnapchatSessions;	// IMP=0x00000001066f0aac
- (_Bool)_shouldKeepMuteOverrideOnDismiss;	// IMP=0x00000001066f0a00
- (void)_restoreNativeVolumeIfNeeded;	// IMP=0x00000001066f09b0
- (void)pageViewControllerWillDealloc:(id)arg1;	// IMP=0x00000001066f0998
- (void)pageViewControllerDidTeardown:(id)arg1;	// IMP=0x00000001066f0980
- (void)pageViewControllerDidLoadView:(id)arg1;	// IMP=0x00000001066f08f0
- (id)jiraMetaInfo;	// IMP=0x00000001066f08e8
- (id)defaultProjectNameV2;	// IMP=0x00000001066f08d8
- (void)modalDismissalDidEnd;	// IMP=0x00000001066f08a0
- (void)modalPresentationDidEnd;	// IMP=0x00000001066f0890
- (void)_invokeCallbacksImmediately;	// IMP=0x00000001066f0744
- (void)requestCallbackWhenViewModelConnectionIsStable:(id)arg1;	// IMP=0x00000001066f059c
- (id)operaSharedResourceManager:(id)arg1 viewModelForRelativePosition:(unsigned long long)arg2;	// IMP=0x00000001066f0554
- (id)uiViewController;	// IMP=0x00000001066f0550
@property(readonly, nonatomic) id <SCOperaUIViewControllerProviding> uiViewControllerProviding;
@property(readonly, nonatomic) id <SCViewControllerTransitionAnimating> transitionAnimating;
- (id)pageNameLogging;	// IMP=0x00000001066f0538
@property(readonly, nonatomic) id <SCOperaInteractionStateProviding> interactionStateProviding;
@property(readonly, nonatomic) id <SCOperaLegacySessionStateContaining> legacySessionStateContaining;
@property(readonly, nonatomic) id <SCOperaEventAnnouncing> eventAnnouncing;
@property(readonly, nonatomic) id <SCModalPresentation> modalPresentation;
@property(readonly, nonatomic) id <SCOperaViewModelConnectionsCallbackControlling> viewModelConnectionsCallbackControlling;
@property(readonly, nonatomic) id <SCOperaZooming> zooming;
@property(readonly, nonatomic) id <SCOperaShareableMediaItemsProviding> shareableMediaItemsProviding;
- (id)viewDismissing;	// IMP=0x00000001066f0500
- (id)viewControllerTransitionAnimatorDelegate;	// IMP=0x00000001066f04fc
@property(readonly, nonatomic) id <SCOperaViewPlayManaging> viewPlayManaging;
- (void)hideChrome:(_Bool)arg1;	// IMP=0x00000001066f0450
- (void)zoomIn:(_Bool)arg1 completion:(id)arg2;	// IMP=0x00000001066f0324
- (id)_dummyPageViewControllerForViewModel:(id)arg1;	// IMP=0x00000001066f023c
- (void)_clearUpPreviousDummyPageViews;	// IMP=0x00000001066f0098
- (void)_updateFloatingLayer:(id)arg1;	// IMP=0x00000001066efd44
- (void)_addFloatingLayer:(id)arg1;	// IMP=0x00000001066efb6c
- (void)audioSession:(id)arg1 didChangeVolume:(double)arg2;	// IMP=0x00000001066efb68
- (void)audioSessionRouteDidChangeReasonOldDeviceUnavailable:(id)arg1;	// IMP=0x00000001066efb24
- (void)audioSessionRouteDidChangeReasonNewDeviceAvailable:(id)arg1;	// IMP=0x00000001066efb20
- (void)audioSession:(id)arg1 didEndInterruption:(_Bool)arg2;	// IMP=0x00000001066efad0
- (void)audioSessionDidBeginInterruption:(id)arg1;	// IMP=0x00000001066efa38
- (_Bool)_shouldPauseForAudioInterruption;	// IMP=0x00000001066ef9b8
- (_Bool)pageIsAttachmentPage:(id)arg1;	// IMP=0x00000001066ef92c
- (void)setImageForBackdrop:(id)arg1;	// IMP=0x00000001066ef928
- (void)setPausedForAttachment:(_Bool)arg1;	// IMP=0x00000001066ef8e0
- (struct UIEdgeInsets)safeInsetsForPage;	// IMP=0x00000001066ef8c8
- (unsigned long long)relativePositionForPageId:(id)arg1;	// IMP=0x00000001066ef450
- (_Bool)pageIsPartiallyVisible:(id)arg1;	// IMP=0x00000001066ef330
- (_Bool)pageIsFullyVisible:(id)arg1;	// IMP=0x00000001066ef260
- (void)deviceOrientationDidChange;	// IMP=0x00000001066ef16c
- (unsigned long long)supportedInterfaceOrientations;	// IMP=0x00000001066ef164
- (void)attachmentInteractionController:(id)arg1 didUpdateAttachmentViewAnchorPointY:(double)arg2;	// IMP=0x00000001066ef060
- (void)attachmentInteractionController:(id)arg1 didUpdateSwipeAngle:(double)arg2 withVerticalTranslation:(double)arg3;	// IMP=0x00000001066eef24
- (void)attachmentInteractionControllerDidDismissAttachment:(id)arg1 swipeDirection:(long long)arg2;	// IMP=0x00000001066eee48
- (_Bool)attachmentInteractionController:(id)arg1 shouldBeginWithSwipeDirection:(long long)arg2 gestureRecognizer:(id)arg3;	// IMP=0x00000001066eeca0
- (void)_disableFadeTransitionForDismissalAnimation;	// IMP=0x00000001066eec88
- (void)_enableFadeTransitionForDismissalAnimation:(id)arg1 fadingViews:(id)arg2;	// IMP=0x00000001066eebc8
- (void)_configureFadeTransitionForDismissalAnimation;	// IMP=0x00000001066eeb08
- (_Bool)viewControllerTransitionAnimatorShouldBeginDismissingWithDirection:(long long)arg1 gestureRecognizer:(id)arg2;	// IMP=0x00000001066eeaf0
- (void)viewControllerTransitionAnimatorDidFinishDismissing:(_Bool)arg1;	// IMP=0x00000001066ee9f0
- (void)viewControllerTransitionAnimatorDidCancelDismissing;	// IMP=0x00000001066ee848
- (void)viewControllerTransitionAnimatorWillBeginAnimatingToDismiss;	// IMP=0x00000001066ee5c0
- (void)viewControllerTransitionAnimatorDidBeginDismissingWithInteraction:(unsigned long long)arg1;	// IMP=0x00000001066ee560
- (void)viewControllerTransitionAnimatorDidBeginDismissing;	// IMP=0x00000001066ee3b8
- (void)viewControllerTransitionAnimatorDidFinishPresenting;	// IMP=0x00000001066ee118
- (void)viewControllerTransitionAnimatorWillBeginPresenting;	// IMP=0x00000001066ee0f4
- (struct CGRect)maskableFrame;	// IMP=0x00000001066ee0dc
- (void)didTriggerEventWithEventName:(id)arg1 announcerIdentifier:(id)arg2 extraData:(id)arg3;	// IMP=0x00000001066edf8c
- (void)dismissWithAnimation:(_Bool)arg1;	// IMP=0x00000001066ede5c
- (void)dismissWithLastInteraction:(id)arg1;	// IMP=0x00000001066eddfc
- (void)dismiss;	// IMP=0x00000001066eddb8
@property(readonly, nonatomic) id <SCViewControllerTransitionAnimating> transitionAnimator;
- (void)updateBaseView:(id)arg1 baseViewOrientation:(long long)arg2 topInset:(double)arg3 transitionMode:(long long)arg4;	// IMP=0x00000001066edd14
- (void)setBaseView:(id)arg1;	// IMP=0x00000001066edbec
- (void)setBaseViewFrame:(struct CGRect)arg1;	// IMP=0x00000001066edbd4
- (void)presentWithTransitionAnimator:(id)arg1;	// IMP=0x00000001066ed930
- (id)_interactionEventWithType:(unsigned long long)arg1 params:(id)arg2;	// IMP=0x00000001066ed7ec
- (void)_shareWebpageURL:(id)arg1;	// IMP=0x00000001066ed618
- (id)_getVerticalNeighborModelForId:(id)arg1 isTopSnap:(_Bool)arg2;	// IMP=0x00000001066ed548
- (_Bool)_currentPageEnablesEagerSwipeUp;	// IMP=0x00000001066ed474
- (void)_updateSwipeUpConfiguration;	// IMP=0x00000001066ed24c
- (_Bool)_extendedAttachmentFrameModeEnabled;	// IMP=0x00000001066ed20c
- (void)_updateAttachmentExtendedModeIfNeeded;	// IMP=0x00000001066ed07c
- (void)operaViewDidSendEvent:(id)arg1 context:(id)arg2 params:(id)arg3;	// IMP=0x00000001066eaefc
- (id)registeredEventsForOperaSession;	// IMP=0x00000001066eada4
- (_Bool)shouldDismissOnViewModel:(id)arg1;	// IMP=0x00000001066ead3c
- (id)currentPageID;	// IMP=0x00000001066eacb4
- (id)_currentPageVC;	// IMP=0x00000001066eac4c
- (struct CGPoint)_currentPageVCOffset;	// IMP=0x00000001066eabd0
- (_Bool)_shouldNotPassCurrentPageWithScrollRelativePosition:(unsigned long long)arg1;	// IMP=0x00000001066ea9f0
- (void)_goBackToPreviousPage;	// IMP=0x00000001066ea6a0
- (void)_didHitDismissViewModel;	// IMP=0x00000001066ea5d8
- (void)_advanceToNextPage:(_Bool)arg1;	// IMP=0x00000001066ea13c
- (_Bool)_shouldPerformForceUpdateOfPageViewControllers;	// IMP=0x00000001066ea050
- (void)navigationManagerOperaScrollViewDidScroll:(id)arg1 direction:(long long)arg2;	// IMP=0x00000001066ea040
- (void)navigationManagerShouldDismiss:(id)arg1;	// IMP=0x00000001066ea034
- (void)navigationManager:(id)arg1 wantsToDismissAnimated:(_Bool)arg2;	// IMP=0x00000001066ea024
- (void)navigationManager:(id)arg1 handledInteraction:(id)arg2;	// IMP=0x00000001066ea010
- (void)navigationManager:(id)arg1 didTapToRelativePosition:(unsigned long long)arg2;	// IMP=0x00000001066e9fa0
- (void)_sendPageDirectionEventWithPreviousViewModel:(id)arg1 nextViewModel:(id)arg2 callback:(id)arg3;	// IMP=0x00000001066e9c68
- (void)_sendPageDirectionEventWithPreviousViewModel:(id)arg1 nextViewModel:(id)arg2;	// IMP=0x00000001066e9c58
- (void)scrollContentViewDidRefreshDisplay:(id)arg1;	// IMP=0x00000001066e9be0
- (void)navigationManager:(id)arg1 didScrollToPageID:(id)arg2 didScrollCallback:(id)arg3;	// IMP=0x00000001066e9ad8
- (id)_viewModelForRelativePosition:(unsigned long long)arg1;	// IMP=0x00000001066e9940
- (id)_pageVCForRelativePosition:(unsigned long long)arg1;	// IMP=0x00000001066e98e0
- (id)shareableMediaSnapshotsWithPerformer:(id)arg1;	// IMP=0x00000001066e9860
- (id)shareableMedias;	// IMP=0x00000001066e980c
- (void)_updatePageIDToPageVCMapWithDimensionToPageIdToPageVCMap:(id)arg1 preloadedPageVCMap:(id)arg2;	// IMP=0x00000001066e9210
- (void)_updateOffsetInActionBarWithDirection:(long long)arg1;	// IMP=0x00000001066e8ff8
- (long long)_actionBarBackgroundStyle;	// IMP=0x00000001066e8fc8
- (void)_enumeratePageViewControllers:(id)arg1;	// IMP=0x00000001066e8dc0
- (void)_updateActionBar;	// IMP=0x00000001066e8bdc
- (void)_addOperaPageViewControllers:(id)arg1;	// IMP=0x00000001066e8964
- (void)_updateOperaScrollViewAndAddPageVCs:(id)arg1;	// IMP=0x00000001066e86a4
- (id)_pageViewControllerForPageID:(id)arg1;	// IMP=0x00000001066e8604
- (id)_pageViewControllerForViewModel:(id)arg1;	// IMP=0x00000001066e837c
- (id)_buildPageVCsForViewModels:(id)arg1 modelIDToPageVCMap:(id)arg2 needToCreateDummyPageVCIfNecessary:(_Bool)arg3;	// IMP=0x00000001066e7f5c
- (void)_logDummyPagesInfoIfNeeded;	// IMP=0x00000001066e7d9c
- (void)_loadPageViewsBasedOnViewModels;	// IMP=0x00000001066e7a80
- (void)_informCurrentPageVCDisappear;	// IMP=0x00000001066e7a18
- (void)_informNeighborPageVCVisibilityForRelativePosition:(unsigned long long)arg1;	// IMP=0x00000001066e7954
- (void)_informNeighborPageVCsVisibility:(_Bool)arg1;	// IMP=0x00000001066e7504
- (void)_scheduleNeighborPageVCsVisibilityInformingIfNeeded;	// IMP=0x00000001066e72d0
- (void)_informCurrentPageVCVisibilityIfNecessary;	// IMP=0x00000001066e7170
- (void)viewModelsManagerDidUpdateLoadedPageIDs;	// IMP=0x00000001066e70e8
- (void)viewModelsManagerWillForcePagingFromViewModel:(id)arg1 toViewModel:(id)arg2;	// IMP=0x00000001066e70dc
- (void)viewModelsManagerDidPageToNilViewModel;	// IMP=0x00000001066e705c
- (void)viewModelsManagerDidHitDismissViewModel;	// IMP=0x00000001066e7050
- (void)_currentPageVCDidStartDisplaying;	// IMP=0x00000001066e6fe4
- (void)_prepareNewCurrentPageViewController;	// IMP=0x00000001066e6be4
- (void)viewModelsManagerDidUpdateViewModel;	// IMP=0x00000001066e6a6c
- (_Bool)isSwipeDownToDismissDisabled;	// IMP=0x00000001066e6a60
- (_Bool)isFullyVisible;	// IMP=0x00000001066e6a50
- (id)operaPresentedViewController;	// IMP=0x00000001066e6a44
- (id)operaViewControllerView;	// IMP=0x00000001066e6a38
- (_Bool)isDismissing;	// IMP=0x00000001066e6a28
- (_Bool)shouldDeferUpdatingPageViewControllers;	// IMP=0x00000001066e6a18
- (_Bool)shouldNotPassCurrentPageWithScrollRelativePosition:(unsigned long long)arg1;	// IMP=0x00000001066e6a0c
- (id)lastViewInteraction;	// IMP=0x00000001066e69fc
- (long long)pageabilityForRelativePosition:(unsigned long long)arg1 gestureRecognizer:(id)arg2;	// IMP=0x00000001066e697c
- (id)dummyPageViewControllers;	// IMP=0x00000001066e696c
- (id)pageViewControllerForViewModel:(id)arg1;	// IMP=0x00000001066e6960
- (id)floatingLayerViewControllers;	// IMP=0x00000001066e6948
- (id)fullyVisiblePageIDForTargetContentOffset:(struct CGPoint)arg1 currentContentOffset:(struct CGPoint)arg2;	// IMP=0x00000001066e6500
- (long long)pageabilityForRelativePosition:(unsigned long long)arg1 swipeDirection:(long long)arg2 gestureRecognizer:(id)arg3;	// IMP=0x00000001066e6420
- (id)pageViewControllerForPageID:(id)arg1;	// IMP=0x00000001066e6414
- (id)pageViewControllerForOperaViewModel:(id)arg1;	// IMP=0x00000001066e6408
- (id)currentFullyAppearedPageViewController;	// IMP=0x00000001066e63f8
- (id)currentPageViewController;	// IMP=0x00000001066e63ec
@property(retain, nonatomic) SCOperaViewModel *currentViewModel;
- (id)currentViewModelPageProperties;	// IMP=0x00000001066e634c
@property(readonly, nonatomic) id <SCOperaCurrentViewModelPagePropertiesProviding> pagePropertiesProviding;
- (void)_addPageViewController:(id)arg1 atOffset:(struct CGPoint)arg2;	// IMP=0x00000001066e5fa0
- (void)shouldLayoutPageViewController:(id)arg1 atOffset:(struct CGPoint)arg2;	// IMP=0x00000001066e5f94
- (struct CGPoint)operaScrollViewContentOffsetForCurrentViewModel;	// IMP=0x00000001066e5f80
- (struct CGSize)operaPageSize;	// IMP=0x00000001066e5f6c
- (void)setVolume:(double)arg1;	// IMP=0x00000001066e5e5c
- (void)setLooping:(_Bool)arg1;	// IMP=0x00000001066e5e14
- (void)restartTimer;	// IMP=0x00000001066e5dd4
- (void)resume;	// IMP=0x00000001066e5c5c
- (void)pauseWithOverlay:(_Bool)arg1;	// IMP=0x00000001066e5bf0
- (id)pageViewName;	// IMP=0x00000001066e5b9c
- (id)_presentedViewControllerOrTopVCForSilentlyPresentedProtocol;	// IMP=0x00000001066e5928
- (_Bool)_isPresentedViewControllerAlwaysSilentlyPresented;	// IMP=0x00000001066e5888
- (_Bool)_isPresentingSilentlyPresentedAndPauseOperaViewController;	// IMP=0x00000001066e580c
- (_Bool)_isPresentingSilentlyPresentedViewControllerIncludingPause:(_Bool)arg1;	// IMP=0x00000001066e5694
- (void)didTakeScreenRecord;	// IMP=0x00000001066e55d4
- (void)didTakeScreenshot;	// IMP=0x00000001066e5514
- (void)viewWillResignActive;	// IMP=0x00000001066e5440
- (void)didBecomeActive;	// IMP=0x00000001066e5434
- (void)didBecomeActivePostponed;	// IMP=0x00000001066e52ac
- (void)didMoveToParentViewController:(id)arg1;	// IMP=0x00000001066e5250
- (void)willMoveToParentViewController:(id)arg1;	// IMP=0x00000001066e521c
- (void)viewWillEnterForeground;	// IMP=0x00000001066e4f7c
- (void)viewWillEnterBackground;	// IMP=0x00000001066e4cc0
- (void)viewWillFullyDisappear;	// IMP=0x00000001066e4ca8
- (void)viewDidFullyDisappear:(_Bool)arg1;	// IMP=0x00000001066e45f8
- (void)viewDidFullyAppear;	// IMP=0x00000001066e440c
- (void)dismissViewControllerAnimated:(_Bool)arg1 completion:(id)arg2;	// IMP=0x00000001066e43d8
- (void)presentViewController:(id)arg1 animated:(_Bool)arg2 completion:(id)arg3;	// IMP=0x00000001066e43a4
- (void)viewDidDisappear:(_Bool)arg1;	// IMP=0x00000001066e4148
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x00000001066e4004
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x00000001066e3f4c
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x00000001066e3b7c
- (id)operaView;	// IMP=0x00000001066e3b70
- (void)loadView;	// IMP=0x00000001066e39cc
- (void)viewDidLayoutSubviews;	// IMP=0x00000001066e379c
- (_Bool)prefersStatusBarHidden;	// IMP=0x00000001066e3724
- (void)updateModelsToPreload:(id)arg1;	// IMP=0x00000001066e370c
- (void)removeObservers;	// IMP=0x00000001066e36f0
- (void)addObservers;	// IMP=0x00000001066e3580
- (void)dealloc;	// IMP=0x00000001066e351c
- (id)initWithConfiguration:(id)arg1 operaDependencies:(id)arg2 eventAnnouncer:(id)arg3 viewModelsManager:(id)arg4 customVolumeController:(id)arg5 notificationCenter:(id)arg6 sharedResourceManager:(id)arg7;	// IMP=0x00000001066e2dec
- (id)initWithConfiguration:(id)arg1 operaDependencies:(id)arg2 initialViewModel:(id)arg3 eventAnnouncer:(id)arg4;	// IMP=0x00000001066e2c20
- (id)initWithConfiguration:(id)arg1 operaDependencies:(id)arg2 initialViewModel:(id)arg3;	// IMP=0x00000001066e2b60
- (id)initWithConfiguration:(id)arg1 operaDependencies:(id)arg2 initialViewModel:(id)arg3 sessions:(id)arg4;	// IMP=0x00000001066e29bc

// Remaining properties
@property(retain, nonatomic) id <SCNavigationLogging> PPVNavigationLogger;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

