//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//
#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
@class NSArray, NSString, SIGAlertDialogButton, SIGLabel, SIGTextField, SIGTextView, UIScrollView, UIView;

@interface SIGAlertDialog : UIViewController
{
    SIGLabel *_titleLabel;
    SIGTextView *_dialogTextView;
    SIGTextField *_editTextField;
    UIView *_accessoryView;
    unsigned long long _accessoryLayoutStyle;
    NSArray *_actionButtons;
    SIGAlertDialogButton *_activeButton;
    UIView *_containerView;
    UIScrollView *_scrollView;
    _Bool _editModeEnabled;
    id _linkHandler;
    _Bool _loading;
}

+ (id)_imageViewForImage:(id)arg1;	// IMP=0x0000000106f9c8e8
+ (id)editableAlertWithTitle:(id)arg1 dialogText:(id)arg2 saveAction:(id)arg3 cancelAction:(id)arg4;	// IMP=0x0000000106f9b8f4
+ (id)_alertWithTitle:(id)arg1 description:(id)arg2;	// IMP=0x0000000105d439b8
+ (id)lowStorageAlert;	// IMP=0x0000000105d43924
+ (id)highTemperatureAlert;	// IMP=0x0000000105d43890
+ (id)lowTemperatureAlert;	// IMP=0x0000000105d437fc
+ (id)lowBatteryAlertForDevice:(id)arg1;	// IMP=0x0000000105d435dc
+ (id)alertForModulerCameraErrorWithCompletion:(id)arg1;	// IMP=0x0000000106dfd0a8
@property(nonatomic) unsigned long long accessoryLayoutStyle; // @synthesize accessoryLayoutStyle=_accessoryLayoutStyle;
@property(nonatomic, getter=isLoading) _Bool loading; // @synthesize loading=_loading;
- (id)getCancelButton;	// IMP=0x0000000106f9e640
- (void)viewDidLayoutSubviews;	// IMP=0x0000000106f9e5d0
- (void)_setupAutolayout;	// IMP=0x0000000106f9d5a8
- (void)_setAccessoryView:(id)arg1;	// IMP=0x0000000106f9d518
- (void)_setTitle:(id)arg1;	// IMP=0x0000000106f9d3e4
- (void)_handleTapForButton:(id)arg1 withAction:(id)arg2;	// IMP=0x0000000106f9d374
- (void)_setActions:(id)arg1;	// IMP=0x0000000106f9cec4
- (void)_setEditModeEnabled:(_Bool)arg1;	// IMP=0x0000000106f9cde4
- (void)_setDialogText:(id)arg1 placeholders:(id)arg2 urlStrings:(id)arg3;	// IMP=0x0000000106f9cbe4
- (_Bool)textView:(id)arg1 shouldInteractWithURL:(id)arg2 inRange:(struct _NSRange)arg3 interaction:(long long)arg4;	// IMP=0x0000000106f9cb3c
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x0000000106f9c7e0
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0000000106f9c75c
- (void)viewDidLoad;	// IMP=0x0000000106f9c364
@property(copy, nonatomic) NSString *editTextFieldPlaceholder;
@property(nonatomic, getter=isSecureTextEntry) _Bool secureTextEntry;
- (void)setSelectedTextRange:(struct _NSRange)arg1;	// IMP=0x0000000106f9c180
@property(copy, nonatomic) NSString *textEntered;
- (id)initWithAccessoryView:(id)arg1 title:(id)arg2 dialogText:(id)arg3 editMode:(_Bool)arg4 actions:(id)arg5 placeholders:(id)arg6 urlStrings:(id)arg7 linkHandler:(id)arg8;	// IMP=0x0000000106f9bde4
- (id)initWithAccessoryView:(id)arg1 title:(id)arg2 dialogText:(id)arg3 editMode:(_Bool)arg4 actions:(id)arg5;	// IMP=0x0000000106f9bdb8
- (id)initWithTitle:(id)arg1 actions:(id)arg2;	// IMP=0x0000000106f9bd98
- (id)initWithImage:(id)arg1 title:(id)arg2 dialogText:(id)arg3 editMode:(_Bool)arg4 actions:(id)arg5 placeholders:(id)arg6 urlStrings:(id)arg7 linkHandler:(id)arg8;	// IMP=0x0000000106f9bc44
- (id)initWithImage:(id)arg1 title:(id)arg2 dialogText:(id)arg3 editMode:(_Bool)arg4 actions:(id)arg5;	// IMP=0x0000000106f9bb4c
- (id)initWithImage:(id)arg1 title:(id)arg2 dialogText:(id)arg3 actions:(id)arg4;	// IMP=0x0000000106f9ba60
- (id)initWithTitle:(id)arg1 dialogText:(id)arg2 actions:(id)arg3;	// IMP=0x0000000106f9ba40
- (id)initWithDialogText:(id)arg1 actions:(id)arg2;
@end

