//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>


@class NSLayoutConstraint, NSObject, NSString, SIGHeaderItemKeyValueObserver, SIGHeaderTitle, SIGHeaderTitleRowAccessoryViewContainer, UILayoutGuide, UITextField;
@protocol SIGHeaderItem, SIGTooltipPresenter;

@interface SIGHeaderTitleRow : UIView
{
    SIGHeaderTitle *_title;
    id *_leadingAccessoryViewContainer;
    id *_trailingAccessoryViewContainer;
    NSLayoutConstraint *_widthConstraint;
    NSObject<SIGHeaderItem> *_incomingHeaderItem;
    id *_headerItemKeyValueObserver;
    unsigned long long _style;
    _Bool _ignoresRTL;
    NSObject<SIGHeaderItem> *_headerItem;
    id <SIGTooltipPresenter> _tooltipPresenter;
    UILayoutGuide *_titleAreaLayoutGuide;
}

@property(readonly, nonatomic) UILayoutGuide *titleAreaLayoutGuide; // @synthesize titleAreaLayoutGuide=_titleAreaLayoutGuide; tooltipPresenter=_tooltipPresenter;
@property(readonly, nonatomic) NSObject<SIGHeaderItem> *headerItem; // @synthesize headerItem=_headerItem;
- (id)performTransitionToHeaderItem:(id)arg1 style:(long long)arg2;	// IMP=0x0000000106fbe5f8
- (void)completeAnimation:(_Bool)arg1;	// IMP=0x0000000106fbe550
- (void)updateConstraints;	// IMP=0x0000000100175d58
- (void)headerItem:(id)arg1 didChangeDismissalAction:(unsigned long long)arg2;	// IMP=0x0000000100173898
- (void)headerItem:(id)arg1 didChangeStyle:(unsigned long long)arg2;	// IMP=0x0000000100172660
- (void)headerItem:(id)arg1 didChangeTrailingAccessoryView:(id)arg2;	// IMP=0x0000000100172700
- (void)headerItem:(id)arg1 didChangeTrailingAccessoryViewHidden:(_Bool)arg2;	// IMP=0x0000000100173584
- (void)headerItem:(id)arg1 didChangeCustomLeadingAccessoryView:(id)arg2;	// IMP=0x00000001001735d8
- (void)headerItem:(id)arg1 didChangeCustomLeadingAccessoryViewHidden:(_Bool)arg2;	// IMP=0x0000000100173844
- (void)_postAnimationUpdatesForAccessoryContainer:(id)arg1;	// IMP=0x00000001001731f4
- (id)_updateLeadingAccessoryViewWithStyle:(long long)arg1;	// IMP=0x0000000100173670
- (id)_leadingAccessoryViewFromHeaderItem:(id)arg1;	// IMP=0x000000010017374c
- (void)_pressedDismiss;	// IMP=0x0000000106fbe498
- (id)_backButton;	// IMP=0x0000000106fbe3ac
- (id)_dismissButton;	// IMP=0x0000000106fbe2c0
- (void)headerItem:(id)arg1 didChangeIgnoreRTL:(_Bool)arg2;	// IMP=0x000000010017267c
- (void)_updateTitleWidthAnchorConstraint;	// IMP=0x0000000100173454
- (void)setHeaderItem:(id)arg1;	// IMP=0x000000010016ddb8
- (void)setFrame:(struct CGRect)arg1;	// IMP=0x000000010016d7c4
- (struct CGSize)intrinsicContentSize;	// IMP=0x0000000106fbe2a8
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;	// IMP=0x0000000106fbe0f4
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;	// IMP=0x0000000106fbe080
- (void)setTitleOpacity:(double)arg1;	// IMP=0x0000000106fbdff4
@property(readonly, nonatomic) UITextField *titleTextField;
@property(readonly, nonatomic) UIView *leadingView;
@property(readonly, nonatomic) UIView *trailingView;
@property(readonly, nonatomic) UIView *titleView;
- (id)initWithHeaderItem:(id)arg1;	// IMP=0x000000010016d538

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) NSUInteger hash;
@property(readonly) Class superclass;

@end

