//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UILabel.h>

@class NSAttributedString, UIFont;

@interface SIGLabel : UILabel
{
    unsigned long long _typographicalStyle;
    unsigned long long _typographicalModifiers;
    NSAttributedString *_attributedString;
}

@property(retain, nonatomic) NSAttributedString *attributedString; // @synthesize attributedString=_attributedString;
@property(nonatomic) unsigned long long typographicalModifiers; // @synthesize typographicalModifiers=_typographicalModifiers;
@property(nonatomic) unsigned long long typographicalStyle; // @synthesize typographicalStyle=_typographicalStyle;
- (void)setAdjustsFontForContentSizeCategory:(_Bool)arg1;	// IMP=0x000000010016e9c4
- (void)didMoveToSuperview;	// IMP=0x000000010016ee50
- (void)_setTextUnchecked:(id)arg1;	// IMP=0x000000010016ea4c
- (void)setAttributedText:(id)arg1;	// IMP=0x0000000106fc2534
- (void)setText:(id)arg1;	// IMP=0x000000010016ec54
- (void)setTextAlignment:(long long)arg1;	// IMP=0x000000010016ebac
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x000000010016eec8
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010016e968

// Remaining properties
@property(retain, nonatomic) UIFont *font; // @dynamic font;

@end

