//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIKit.h>

@class UIImageView, UIImpactFeedbackGenerator, UINotificationFeedbackGenerator;

@interface SIGPullToRefreshGhostView : UIView{
    unsigned long long _state;
    UIImageView *_defaultBody;
    UIImageView *_winkBody;
    UIImageView *_shockedBody;
    UIImageView *_rainbowBody;
    UIImpactFeedbackGenerator *_impactFeedbackGenerator;
    UINotificationFeedbackGenerator *_notificationFeedbackGenerator;
    _Bool _rainbow;
    double _offset;
}

// IMP=0x0000000106fcd974
@property(nonatomic) _Bool rainbow; // @synthesize rainbow=_rainbow;
@property(nonatomic) double offset; // @synthesize offset=_offset;
- (void)_setBodyForState:(unsigned long long)arg1;	// IMP=0x0000000106fcd854
- (void)_setState:(unsigned long long)arg1;	// IMP=0x0000000106fcd598
- (void)_addChild:(id)arg1;	// IMP=0x0000000106fcd218
- (struct CGSize)intrinsicContentSize;	// IMP=0x0000000106fcd204
- (id)init;	// IMP=0x0000000106fccf2c

@end
